#!/usr/bin/env zsh

function tn
{
    if [ -n $1 ] ; then
        c $1
    fi

    local CWD="$(pwd)"
    local PROJ="$(basename ${CWD})"

    tmux new-session -s ${PROJ}

    c - > /dev/null
}

tn $@
